/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.management.system;

/**
 *
 * @author gatka
 */
public class userOptions extends javax.swing.JFrame {

    /**
     * Creates new form userOptions
     */
    public userOptions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userOptionsHeader = new javax.swing.JPanel();
        chooseOptionHeader = new javax.swing.JLabel();
        userOptionsBackground = new javax.swing.JPanel();
        Admin = new javax.swing.JButton();
        Lecturer = new javax.swing.JButton();
        Student = new javax.swing.JButton();
        projectManager = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Choose your Role");
        setPreferredSize(new java.awt.Dimension(900, 750));

        userOptionsHeader.setBackground(new java.awt.Color(255, 204, 204));

        chooseOptionHeader.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        chooseOptionHeader.setForeground(new java.awt.Color(255, 102, 102));
        chooseOptionHeader.setText("Choose Your Role :");

        javax.swing.GroupLayout userOptionsHeaderLayout = new javax.swing.GroupLayout(userOptionsHeader);
        userOptionsHeader.setLayout(userOptionsHeaderLayout);
        userOptionsHeaderLayout.setHorizontalGroup(
            userOptionsHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userOptionsHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chooseOptionHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280))
        );
        userOptionsHeaderLayout.setVerticalGroup(
            userOptionsHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userOptionsHeaderLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(chooseOptionHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        userOptionsBackground.setBackground(new java.awt.Color(242, 219, 179));

        Admin.setBackground(new java.awt.Color(255, 204, 204));
        Admin.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        Admin.setForeground(new java.awt.Color(255, 102, 102));
        Admin.setText("Admin");

        Lecturer.setBackground(new java.awt.Color(255, 204, 204));
        Lecturer.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        Lecturer.setForeground(new java.awt.Color(255, 102, 102));
        Lecturer.setText("Lecturer");

        Student.setBackground(new java.awt.Color(255, 204, 204));
        Student.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        Student.setForeground(new java.awt.Color(255, 102, 102));
        Student.setText("Student");

        projectManager.setBackground(new java.awt.Color(255, 204, 204));
        projectManager.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        projectManager.setForeground(new java.awt.Color(255, 102, 102));
        projectManager.setText("Project Manager");
        projectManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectManagerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userOptionsBackgroundLayout = new javax.swing.GroupLayout(userOptionsBackground);
        userOptionsBackground.setLayout(userOptionsBackgroundLayout);
        userOptionsBackgroundLayout.setHorizontalGroup(
            userOptionsBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userOptionsBackgroundLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(userOptionsBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Student, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(userOptionsBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(projectManager, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(Lecturer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        userOptionsBackgroundLayout.setVerticalGroup(
            userOptionsBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userOptionsBackgroundLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(userOptionsBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(userOptionsBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectManager, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Student, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userOptionsHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(userOptionsBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(userOptionsHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userOptionsBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void projectManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectManagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectManagerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Admin;
    public javax.swing.JButton Lecturer;
    public javax.swing.JButton Student;
    public javax.swing.JLabel chooseOptionHeader;
    public javax.swing.JButton projectManager;
    public javax.swing.JPanel userOptionsBackground;
    public javax.swing.JPanel userOptionsHeader;
    // End of variables declaration//GEN-END:variables
}
