/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.management.system;

/**
 *
 * @author gatka
 */
public class welcomePage extends javax.swing.JFrame {

    /**
     * Creates new form welcomePage
     */
    public welcomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeHeader = new javax.swing.JPanel();
        AGH = new javax.swing.JLabel();
        PMS = new javax.swing.JLabel();
        welcomeBackground = new javax.swing.JPanel();
        schoolIcon = new javax.swing.JLabel();
        startBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to Academic Guidance Hub");
        setPreferredSize(new java.awt.Dimension(900, 750));

        welcomeHeader.setBackground(new java.awt.Color(255, 204, 204));

        AGH.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 48)); // NOI18N
        AGH.setForeground(new java.awt.Color(255, 255, 255));
        AGH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AGH.setLabelFor(AGH);
        AGH.setText("Academic Guidance Hub");
        AGH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        PMS.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        PMS.setForeground(new java.awt.Color(255, 102, 102));
        PMS.setText("Project Management System");

        javax.swing.GroupLayout welcomeHeaderLayout = new javax.swing.GroupLayout(welcomeHeader);
        welcomeHeader.setLayout(welcomeHeaderLayout);
        welcomeHeaderLayout.setHorizontalGroup(
            welcomeHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(welcomeHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomeHeaderLayout.createSequentialGroup()
                        .addComponent(AGH)
                        .addGap(213, 213, 213))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomeHeaderLayout.createSequentialGroup()
                        .addComponent(PMS)
                        .addGap(278, 278, 278))))
        );
        welcomeHeaderLayout.setVerticalGroup(
            welcomeHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeHeaderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(AGH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PMS)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        welcomeBackground.setBackground(new java.awt.Color(242, 219, 179));
        welcomeBackground.setPreferredSize(new java.awt.Dimension(900, 608));

        schoolIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\gatka\\Downloads\\Image\\167707.png")); // NOI18N

        startBtn.setBackground(new java.awt.Color(255, 255, 204));
        startBtn.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 36)); // NOI18N
        startBtn.setForeground(new java.awt.Color(255, 204, 102));
        startBtn.setText("START");
        startBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout welcomeBackgroundLayout = new javax.swing.GroupLayout(welcomeBackground);
        welcomeBackground.setLayout(welcomeBackgroundLayout);
        welcomeBackgroundLayout.setHorizontalGroup(
            welcomeBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeBackgroundLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(schoolIcon)
                .addGap(75, 75, 75)
                .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        welcomeBackgroundLayout.setVerticalGroup(
            welcomeBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeBackgroundLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(schoolIcon)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomeBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
        );

        startBtn.getAccessibleContext().setAccessibleName("startBtn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomeHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(welcomeBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(welcomeHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_startBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel AGH;
    public javax.swing.JLabel PMS;
    private javax.swing.JLabel schoolIcon;
    public javax.swing.JButton startBtn;
    public javax.swing.JPanel welcomeBackground;
    public javax.swing.JPanel welcomeHeader;
    // End of variables declaration//GEN-END:variables
}
